/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminChatsRouteImport } from './routes/admin.chats'
import { Route as AdminCreatorsRouteImport } from './routes/admin.creators'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminFraudRouteImport } from './routes/admin.fraud'
import { Route as AdminGamesRouteImport } from './routes/admin.games'
import { Route as AdminGiftsRouteImport } from './routes/admin.gifts'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminVideoLogsRouteImport } from './routes/admin.video-logs'
import { Route as AdminVoiceLogsRouteImport } from './routes/admin.voice-logs'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminWithdrawalsRouteImport } from './routes/admin.withdrawals'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppCreatorsRouteImport } from './routes/app.creators'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppGiftsRouteImport } from './routes/app.gifts'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppRewardsRouteImport } from './routes/app.rewards'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as CreatorChatRouteImport } from './routes/creator.chat'
import { Route as CreatorEarningsRouteImport } from './routes/creator.earnings'
import { Route as CreatorGalleryRouteImport } from './routes/creator.gallery'
import { Route as CreatorGiftsRouteImport } from './routes/creator.gifts'
import { Route as CreatorKycRouteImport } from './routes/creator.kyc'
import { Route as CreatorPricingRouteImport } from './routes/creator.pricing'
import { Route as CreatorProfileRouteImport } from './routes/creator.profile'
import { Route as CreatorReviewsRouteImport } from './routes/creator.reviews'
import { Route as CreatorSettingsRouteImport } from './routes/creator.settings'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as LegalAboutRouteImport } from './routes/legal.about'
import { Route as LegalCommunityRouteImport } from './routes/legal.community'
import { Route as LegalContactRouteImport } from './routes/legal.contact'
import { Route as LegalFaqRouteImport } from './routes/legal.faq'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalSafetyRouteImport } from './routes/legal.safety'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as AppChatIndexRouteImport } from './routes/app.chat.index'
import { Route as AppChatIdRouteImport } from './routes/app.chat.$id'
import { Route as AppCreatorIdRouteImport } from './routes/app.creator.$id'
import { Route as AppGamesIndexRouteImport } from './routes/app.games.index'
import { Route as AppGamesColorConnectRouteImport } from './routes/app.games.color-connect'
import { Route as AppGamesLeaderboardRouteImport } from './routes/app.games.leaderboard'
import { Route as AppGamesScratchRouteImport } from './routes/app.games.scratch'
import { Route as AppProfileEditRouteImport } from './routes/app.profile.edit'
import { Route as AppWalletIndexRouteImport } from './routes/app.wallet.index'
import { Route as AppWalletBuyRouteImport } from './routes/app.wallet.buy'
import { Route as AppWalletTransactionsRouteImport } from './routes/app.wallet.transactions'
import { Route as CreatorChatIdRouteImport } from './routes/creator.chat.$id'
import { Route as AppCallVideoIdRouteImport } from './routes/app.call.video.$id'
import { Route as AppCallVoiceIdRouteImport } from './routes/app.call.voice.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatsRoute = AdminChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorsRoute = AdminCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/fraud',
  path: '/fraud',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGamesRoute = AdminGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGiftsRoute = AdminGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideoLogsRoute = AdminVideoLogsRouteImport.update({
  id: '/video-logs',
  path: '/video-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVoiceLogsRoute = AdminVoiceLogsRouteImport.update({
  id: '/voice-logs',
  path: '/voice-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWithdrawalsRoute = AdminWithdrawalsRouteImport.update({
  id: '/withdrawals',
  path: '/withdrawals',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorsRoute = AppCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppGiftsRoute = AppGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRewardsRoute = AppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorChatRoute = CreatorChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorEarningsRoute = CreatorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorGalleryRoute = CreatorGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorGiftsRoute = CreatorGiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorKycRoute = CreatorKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorPricingRoute = CreatorPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProfileRoute = CreatorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorReviewsRoute = CreatorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSettingsRoute = CreatorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CreatorRoute,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAboutRoute = LegalAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCommunityRoute = LegalCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => LegalRoute,
} as any)
const LegalContactRoute = LegalContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LegalRoute,
} as any)
const LegalFaqRoute = LegalFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => LegalRoute,
} as any)
const LegalSafetyRoute = LegalSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => LegalRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const AppChatIndexRoute = AppChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AppRoute,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCreatorIdRoute = AppCreatorIdRouteImport.update({
  id: '/creator/$id',
  path: '/creator/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesColorConnectRoute = AppGamesColorConnectRouteImport.update({
  id: '/games/color-connect',
  path: '/games/color-connect',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesLeaderboardRoute = AppGamesLeaderboardRouteImport.update({
  id: '/games/leaderboard',
  path: '/games/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesScratchRoute = AppGamesScratchRouteImport.update({
  id: '/games/scratch',
  path: '/games/scratch',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileEditRoute = AppProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppWalletIndexRoute = AppWalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletBuyRoute = AppWalletBuyRouteImport.update({
  id: '/wallet/buy',
  path: '/wallet/buy',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletTransactionsRoute = AppWalletTransactionsRouteImport.update({
  id: '/wallet/transactions',
  path: '/wallet/transactions',
  getParentRoute: () => AppRoute,
} as any)
const CreatorChatIdRoute = CreatorChatIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CreatorChatRoute,
} as any)
const AppCallVideoIdRoute = AppCallVideoIdRouteImport.update({
  id: '/call/video/$id',
  path: '/call/video/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCallVoiceIdRoute = AppCallVoiceIdRouteImport.update({
  id: '/call/voice/$id',
  path: '/call/voice/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/gifts': typeof AdminGiftsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/video-logs': typeof AdminVideoLogsRoute
  '/admin/voice-logs': typeof AdminVoiceLogsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/creators': typeof AppCreatorsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/gifts': typeof AppGiftsRoute
  '/app/help': typeof AppHelpRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/rewards': typeof AppRewardsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/creator/chat': typeof CreatorChatRouteWithChildren
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/gallery': typeof CreatorGalleryRoute
  '/creator/gifts': typeof CreatorGiftsRoute
  '/creator/kyc': typeof CreatorKycRoute
  '/creator/pricing': typeof CreatorPricingRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/reviews': typeof CreatorReviewsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/community': typeof LegalCommunityRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/safety': typeof LegalSafetyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/creator/$id': typeof AppCreatorIdRoute
  '/app/games/color-connect': typeof AppGamesColorConnectRoute
  '/app/games/leaderboard': typeof AppGamesLeaderboardRoute
  '/app/games/scratch': typeof AppGamesScratchRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/wallet/buy': typeof AppWalletBuyRoute
  '/app/wallet/transactions': typeof AppWalletTransactionsRoute
  '/creator/chat/$id': typeof CreatorChatIdRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/games/': typeof AppGamesIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
  '/app/call/video/$id': typeof AppCallVideoIdRoute
  '/app/call/voice/$id': typeof AppCallVoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/gifts': typeof AdminGiftsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/video-logs': typeof AdminVideoLogsRoute
  '/admin/voice-logs': typeof AdminVoiceLogsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/creators': typeof AppCreatorsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/gifts': typeof AppGiftsRoute
  '/app/help': typeof AppHelpRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/rewards': typeof AppRewardsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/creator/chat': typeof CreatorChatRouteWithChildren
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/gallery': typeof CreatorGalleryRoute
  '/creator/gifts': typeof CreatorGiftsRoute
  '/creator/kyc': typeof CreatorKycRoute
  '/creator/pricing': typeof CreatorPricingRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/reviews': typeof CreatorReviewsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/community': typeof LegalCommunityRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/safety': typeof LegalSafetyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/legal': typeof LegalIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/creator/$id': typeof AppCreatorIdRoute
  '/app/games/color-connect': typeof AppGamesColorConnectRoute
  '/app/games/leaderboard': typeof AppGamesLeaderboardRoute
  '/app/games/scratch': typeof AppGamesScratchRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/wallet/buy': typeof AppWalletBuyRoute
  '/app/wallet/transactions': typeof AppWalletTransactionsRoute
  '/creator/chat/$id': typeof CreatorChatIdRoute
  '/app/chat': typeof AppChatIndexRoute
  '/app/games': typeof AppGamesIndexRoute
  '/app/wallet': typeof AppWalletIndexRoute
  '/app/call/video/$id': typeof AppCallVideoIdRoute
  '/app/call/voice/$id': typeof AppCallVoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/chats': typeof AdminChatsRoute
  '/admin/creators': typeof AdminCreatorsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/games': typeof AdminGamesRoute
  '/admin/gifts': typeof AdminGiftsRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/video-logs': typeof AdminVideoLogsRoute
  '/admin/voice-logs': typeof AdminVoiceLogsRoute
  '/admin/wallets': typeof AdminWalletsRoute
  '/admin/withdrawals': typeof AdminWithdrawalsRoute
  '/app/creators': typeof AppCreatorsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/gifts': typeof AppGiftsRoute
  '/app/help': typeof AppHelpRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRouteWithChildren
  '/app/rewards': typeof AppRewardsRoute
  '/app/search': typeof AppSearchRoute
  '/app/settings': typeof AppSettingsRoute
  '/creator/chat': typeof CreatorChatRouteWithChildren
  '/creator/earnings': typeof CreatorEarningsRoute
  '/creator/gallery': typeof CreatorGalleryRoute
  '/creator/gifts': typeof CreatorGiftsRoute
  '/creator/kyc': typeof CreatorKycRoute
  '/creator/pricing': typeof CreatorPricingRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/reviews': typeof CreatorReviewsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/legal/about': typeof LegalAboutRoute
  '/legal/community': typeof LegalCommunityRoute
  '/legal/contact': typeof LegalContactRoute
  '/legal/faq': typeof LegalFaqRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/safety': typeof LegalSafetyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/legal/': typeof LegalIndexRoute
  '/app/chat/$id': typeof AppChatIdRoute
  '/app/creator/$id': typeof AppCreatorIdRoute
  '/app/games/color-connect': typeof AppGamesColorConnectRoute
  '/app/games/leaderboard': typeof AppGamesLeaderboardRoute
  '/app/games/scratch': typeof AppGamesScratchRoute
  '/app/profile/edit': typeof AppProfileEditRoute
  '/app/wallet/buy': typeof AppWalletBuyRoute
  '/app/wallet/transactions': typeof AppWalletTransactionsRoute
  '/creator/chat/$id': typeof CreatorChatIdRoute
  '/app/chat/': typeof AppChatIndexRoute
  '/app/games/': typeof AppGamesIndexRoute
  '/app/wallet/': typeof AppWalletIndexRoute
  '/app/call/video/$id': typeof AppCallVideoIdRoute
  '/app/call/voice/$id': typeof AppCallVoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/creator'
    | '/forgot-password'
    | '/legal'
    | '/login'
    | '/signup'
    | '/verify-otp'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/creators'
    | '/admin/customers'
    | '/admin/fraud'
    | '/admin/games'
    | '/admin/gifts'
    | '/admin/kyc'
    | '/admin/legal'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/video-logs'
    | '/admin/voice-logs'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/app/creators'
    | '/app/favorites'
    | '/app/gifts'
    | '/app/help'
    | '/app/notifications'
    | '/app/profile'
    | '/app/rewards'
    | '/app/search'
    | '/app/settings'
    | '/creator/chat'
    | '/creator/earnings'
    | '/creator/gallery'
    | '/creator/gifts'
    | '/creator/kyc'
    | '/creator/pricing'
    | '/creator/profile'
    | '/creator/reviews'
    | '/creator/settings'
    | '/legal/about'
    | '/legal/community'
    | '/legal/contact'
    | '/legal/faq'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/safety'
    | '/legal/terms'
    | '/admin/'
    | '/app/'
    | '/creator/'
    | '/legal/'
    | '/app/chat/$id'
    | '/app/creator/$id'
    | '/app/games/color-connect'
    | '/app/games/leaderboard'
    | '/app/games/scratch'
    | '/app/profile/edit'
    | '/app/wallet/buy'
    | '/app/wallet/transactions'
    | '/creator/chat/$id'
    | '/app/chat/'
    | '/app/games/'
    | '/app/wallet/'
    | '/app/call/video/$id'
    | '/app/call/voice/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/verify-otp'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/creators'
    | '/admin/customers'
    | '/admin/fraud'
    | '/admin/games'
    | '/admin/gifts'
    | '/admin/kyc'
    | '/admin/legal'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/video-logs'
    | '/admin/voice-logs'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/app/creators'
    | '/app/favorites'
    | '/app/gifts'
    | '/app/help'
    | '/app/notifications'
    | '/app/profile'
    | '/app/rewards'
    | '/app/search'
    | '/app/settings'
    | '/creator/chat'
    | '/creator/earnings'
    | '/creator/gallery'
    | '/creator/gifts'
    | '/creator/kyc'
    | '/creator/pricing'
    | '/creator/profile'
    | '/creator/reviews'
    | '/creator/settings'
    | '/legal/about'
    | '/legal/community'
    | '/legal/contact'
    | '/legal/faq'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/safety'
    | '/legal/terms'
    | '/admin'
    | '/app'
    | '/creator'
    | '/legal'
    | '/app/chat/$id'
    | '/app/creator/$id'
    | '/app/games/color-connect'
    | '/app/games/leaderboard'
    | '/app/games/scratch'
    | '/app/profile/edit'
    | '/app/wallet/buy'
    | '/app/wallet/transactions'
    | '/creator/chat/$id'
    | '/app/chat'
    | '/app/games'
    | '/app/wallet'
    | '/app/call/video/$id'
    | '/app/call/voice/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/creator'
    | '/forgot-password'
    | '/legal'
    | '/login'
    | '/signup'
    | '/verify-otp'
    | '/admin/ads'
    | '/admin/analytics'
    | '/admin/chats'
    | '/admin/creators'
    | '/admin/customers'
    | '/admin/fraud'
    | '/admin/games'
    | '/admin/gifts'
    | '/admin/kyc'
    | '/admin/legal'
    | '/admin/live'
    | '/admin/notifications'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/video-logs'
    | '/admin/voice-logs'
    | '/admin/wallets'
    | '/admin/withdrawals'
    | '/app/creators'
    | '/app/favorites'
    | '/app/gifts'
    | '/app/help'
    | '/app/notifications'
    | '/app/profile'
    | '/app/rewards'
    | '/app/search'
    | '/app/settings'
    | '/creator/chat'
    | '/creator/earnings'
    | '/creator/gallery'
    | '/creator/gifts'
    | '/creator/kyc'
    | '/creator/pricing'
    | '/creator/profile'
    | '/creator/reviews'
    | '/creator/settings'
    | '/legal/about'
    | '/legal/community'
    | '/legal/contact'
    | '/legal/faq'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/safety'
    | '/legal/terms'
    | '/admin/'
    | '/app/'
    | '/creator/'
    | '/legal/'
    | '/app/chat/$id'
    | '/app/creator/$id'
    | '/app/games/color-connect'
    | '/app/games/leaderboard'
    | '/app/games/scratch'
    | '/app/profile/edit'
    | '/app/wallet/buy'
    | '/app/wallet/transactions'
    | '/creator/chat/$id'
    | '/app/chat/'
    | '/app/games/'
    | '/app/wallet/'
    | '/app/call/video/$id'
    | '/app/call/voice/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CreatorRoute: typeof CreatorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chats': {
      id: '/admin/chats'
      path: '/chats'
      fullPath: '/admin/chats'
      preLoaderRoute: typeof AdminChatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creators': {
      id: '/admin/creators'
      path: '/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AdminCreatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/games': {
      id: '/admin/games'
      path: '/games'
      fullPath: '/admin/games'
      preLoaderRoute: typeof AdminGamesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gifts': {
      id: '/admin/gifts'
      path: '/gifts'
      fullPath: '/admin/gifts'
      preLoaderRoute: typeof AdminGiftsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/video-logs': {
      id: '/admin/video-logs'
      path: '/video-logs'
      fullPath: '/admin/video-logs'
      preLoaderRoute: typeof AdminVideoLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/voice-logs': {
      id: '/admin/voice-logs'
      path: '/voice-logs'
      fullPath: '/admin/voice-logs'
      preLoaderRoute: typeof AdminVoiceLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/withdrawals': {
      id: '/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AdminWithdrawalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creators': {
      id: '/app/creators'
      path: '/creators'
      fullPath: '/app/creators'
      preLoaderRoute: typeof AppCreatorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gifts': {
      id: '/app/gifts'
      path: '/gifts'
      fullPath: '/app/gifts'
      preLoaderRoute: typeof AppGiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/rewards': {
      id: '/app/rewards'
      path: '/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AppRewardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/chat': {
      id: '/creator/chat'
      path: '/chat'
      fullPath: '/creator/chat'
      preLoaderRoute: typeof CreatorChatRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/earnings': {
      id: '/creator/earnings'
      path: '/earnings'
      fullPath: '/creator/earnings'
      preLoaderRoute: typeof CreatorEarningsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/gallery': {
      id: '/creator/gallery'
      path: '/gallery'
      fullPath: '/creator/gallery'
      preLoaderRoute: typeof CreatorGalleryRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/gifts': {
      id: '/creator/gifts'
      path: '/gifts'
      fullPath: '/creator/gifts'
      preLoaderRoute: typeof CreatorGiftsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/kyc': {
      id: '/creator/kyc'
      path: '/kyc'
      fullPath: '/creator/kyc'
      preLoaderRoute: typeof CreatorKycRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/pricing': {
      id: '/creator/pricing'
      path: '/pricing'
      fullPath: '/creator/pricing'
      preLoaderRoute: typeof CreatorPricingRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/profile': {
      id: '/creator/profile'
      path: '/profile'
      fullPath: '/creator/profile'
      preLoaderRoute: typeof CreatorProfileRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/reviews': {
      id: '/creator/reviews'
      path: '/reviews'
      fullPath: '/creator/reviews'
      preLoaderRoute: typeof CreatorReviewsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/settings': {
      id: '/creator/settings'
      path: '/settings'
      fullPath: '/creator/settings'
      preLoaderRoute: typeof CreatorSettingsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/about': {
      id: '/legal/about'
      path: '/about'
      fullPath: '/legal/about'
      preLoaderRoute: typeof LegalAboutRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/community': {
      id: '/legal/community'
      path: '/community'
      fullPath: '/legal/community'
      preLoaderRoute: typeof LegalCommunityRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/contact': {
      id: '/legal/contact'
      path: '/contact'
      fullPath: '/legal/contact'
      preLoaderRoute: typeof LegalContactRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/faq': {
      id: '/legal/faq'
      path: '/faq'
      fullPath: '/legal/faq'
      preLoaderRoute: typeof LegalFaqRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/safety': {
      id: '/legal/safety'
      path: '/safety'
      fullPath: '/legal/safety'
      preLoaderRoute: typeof LegalSafetyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/app/chat/': {
      id: '/app/chat/'
      path: '/chat'
      fullPath: '/app/chat/'
      preLoaderRoute: typeof AppChatIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$id': {
      id: '/app/chat/$id'
      path: '/chat/$id'
      fullPath: '/app/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creator/$id': {
      id: '/app/creator/$id'
      path: '/creator/$id'
      fullPath: '/app/creator/$id'
      preLoaderRoute: typeof AppCreatorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games/': {
      id: '/app/games/'
      path: '/games'
      fullPath: '/app/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games/color-connect': {
      id: '/app/games/color-connect'
      path: '/games/color-connect'
      fullPath: '/app/games/color-connect'
      preLoaderRoute: typeof AppGamesColorConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games/leaderboard': {
      id: '/app/games/leaderboard'
      path: '/games/leaderboard'
      fullPath: '/app/games/leaderboard'
      preLoaderRoute: typeof AppGamesLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/games/scratch': {
      id: '/app/games/scratch'
      path: '/games/scratch'
      fullPath: '/app/games/scratch'
      preLoaderRoute: typeof AppGamesScratchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/edit': {
      id: '/app/profile/edit'
      path: '/edit'
      fullPath: '/app/profile/edit'
      preLoaderRoute: typeof AppProfileEditRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/app/wallet/': {
      id: '/app/wallet/'
      path: '/wallet'
      fullPath: '/app/wallet/'
      preLoaderRoute: typeof AppWalletIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/buy': {
      id: '/app/wallet/buy'
      path: '/wallet/buy'
      fullPath: '/app/wallet/buy'
      preLoaderRoute: typeof AppWalletBuyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wallet/transactions': {
      id: '/app/wallet/transactions'
      path: '/wallet/transactions'
      fullPath: '/app/wallet/transactions'
      preLoaderRoute: typeof AppWalletTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/creator/chat/$id': {
      id: '/creator/chat/$id'
      path: '/$id'
      fullPath: '/creator/chat/$id'
      preLoaderRoute: typeof CreatorChatIdRouteImport
      parentRoute: typeof CreatorChatRoute
    }
    '/app/call/video/$id': {
      id: '/app/call/video/$id'
      path: '/call/video/$id'
      fullPath: '/app/call/video/$id'
      preLoaderRoute: typeof AppCallVideoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/call/voice/$id': {
      id: '/app/call/voice/$id'
      path: '/call/voice/$id'
      fullPath: '/app/call/voice/$id'
      preLoaderRoute: typeof AppCallVoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminChatsRoute: typeof AdminChatsRoute
  AdminCreatorsRoute: typeof AdminCreatorsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminGamesRoute: typeof AdminGamesRoute
  AdminGiftsRoute: typeof AdminGiftsRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminVideoLogsRoute: typeof AdminVideoLogsRoute
  AdminVoiceLogsRoute: typeof AdminVoiceLogsRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
  AdminWithdrawalsRoute: typeof AdminWithdrawalsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdsRoute: AdminAdsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminChatsRoute: AdminChatsRoute,
  AdminCreatorsRoute: AdminCreatorsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminGamesRoute: AdminGamesRoute,
  AdminGiftsRoute: AdminGiftsRoute,
  AdminKycRoute: AdminKycRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminVideoLogsRoute: AdminVideoLogsRoute,
  AdminVoiceLogsRoute: AdminVoiceLogsRoute,
  AdminWalletsRoute: AdminWalletsRoute,
  AdminWithdrawalsRoute: AdminWithdrawalsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppProfileRouteChildren {
  AppProfileEditRoute: typeof AppProfileEditRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileEditRoute: AppProfileEditRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppRouteChildren {
  AppCreatorsRoute: typeof AppCreatorsRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppGiftsRoute: typeof AppGiftsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppRewardsRoute: typeof AppRewardsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
  AppCreatorIdRoute: typeof AppCreatorIdRoute
  AppGamesColorConnectRoute: typeof AppGamesColorConnectRoute
  AppGamesLeaderboardRoute: typeof AppGamesLeaderboardRoute
  AppGamesScratchRoute: typeof AppGamesScratchRoute
  AppWalletBuyRoute: typeof AppWalletBuyRoute
  AppWalletTransactionsRoute: typeof AppWalletTransactionsRoute
  AppChatIndexRoute: typeof AppChatIndexRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
  AppWalletIndexRoute: typeof AppWalletIndexRoute
  AppCallVideoIdRoute: typeof AppCallVideoIdRoute
  AppCallVoiceIdRoute: typeof AppCallVoiceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCreatorsRoute: AppCreatorsRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppGiftsRoute: AppGiftsRoute,
  AppHelpRoute: AppHelpRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppRewardsRoute: AppRewardsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
  AppCreatorIdRoute: AppCreatorIdRoute,
  AppGamesColorConnectRoute: AppGamesColorConnectRoute,
  AppGamesLeaderboardRoute: AppGamesLeaderboardRoute,
  AppGamesScratchRoute: AppGamesScratchRoute,
  AppWalletBuyRoute: AppWalletBuyRoute,
  AppWalletTransactionsRoute: AppWalletTransactionsRoute,
  AppChatIndexRoute: AppChatIndexRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
  AppWalletIndexRoute: AppWalletIndexRoute,
  AppCallVideoIdRoute: AppCallVideoIdRoute,
  AppCallVoiceIdRoute: AppCallVoiceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface CreatorChatRouteChildren {
  CreatorChatIdRoute: typeof CreatorChatIdRoute
}

const CreatorChatRouteChildren: CreatorChatRouteChildren = {
  CreatorChatIdRoute: CreatorChatIdRoute,
}

const CreatorChatRouteWithChildren = CreatorChatRoute._addFileChildren(
  CreatorChatRouteChildren,
)

interface CreatorRouteChildren {
  CreatorChatRoute: typeof CreatorChatRouteWithChildren
  CreatorEarningsRoute: typeof CreatorEarningsRoute
  CreatorGalleryRoute: typeof CreatorGalleryRoute
  CreatorGiftsRoute: typeof CreatorGiftsRoute
  CreatorKycRoute: typeof CreatorKycRoute
  CreatorPricingRoute: typeof CreatorPricingRoute
  CreatorProfileRoute: typeof CreatorProfileRoute
  CreatorReviewsRoute: typeof CreatorReviewsRoute
  CreatorSettingsRoute: typeof CreatorSettingsRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorChatRoute: CreatorChatRouteWithChildren,
  CreatorEarningsRoute: CreatorEarningsRoute,
  CreatorGalleryRoute: CreatorGalleryRoute,
  CreatorGiftsRoute: CreatorGiftsRoute,
  CreatorKycRoute: CreatorKycRoute,
  CreatorPricingRoute: CreatorPricingRoute,
  CreatorProfileRoute: CreatorProfileRoute,
  CreatorReviewsRoute: CreatorReviewsRoute,
  CreatorSettingsRoute: CreatorSettingsRoute,
  CreatorIndexRoute: CreatorIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface LegalRouteChildren {
  LegalAboutRoute: typeof LegalAboutRoute
  LegalCommunityRoute: typeof LegalCommunityRoute
  LegalContactRoute: typeof LegalContactRoute
  LegalFaqRoute: typeof LegalFaqRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalSafetyRoute: typeof LegalSafetyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAboutRoute: LegalAboutRoute,
  LegalCommunityRoute: LegalCommunityRoute,
  LegalContactRoute: LegalContactRoute,
  LegalFaqRoute: LegalFaqRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalSafetyRoute: LegalSafetyRoute,
  LegalTermsRoute: LegalTermsRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CreatorRoute: CreatorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
